spring:
  application:
    name: paysgift-userservice
  config:
    activate:
      on-profile: ${APP_ACTIVE}  # This line is fine; it activates the configuration for the 'dev' profile.
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
      properties:
        hibernate.jdbc.time_zone: UTC
        hibernate.timezone.default_storage: NORMALIZE
        hibernate.type.preferred_instant_jdbc_type: TIMESTAMP
        hibernate.id.new_generator_mappings: true
        hibernate.connection.provider_disables_autocommit: true
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: false
        hibernate.jdbc.batch_size: 25
        hibernate.order_inserts: true
        hibernate.order_updates: true
        hibernate.query.fail_on_pagination_over_collection_fetch: true
        hibernate.query.in_clause_parameter_padding: true
      open-in-view: false
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  autoconfigure:
    exclude: org.springframework.boot.actuate.autoconfigure.metrics.jdbc.DataSourcePoolMetricsAutoConfiguration
  docker:
    compose:
      enabled: false
      lifecycle-management: start-only
      file: src/main/docker/mysql.yml
  jmx:
    enabled: false
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - configprops
          - env
          - health
          - info
          - jhimetrics
          - jhiopenapigroups
          - logfile
          - loggers
          - prometheus
          - threaddump
          - caches
          - liquibase
  endpoint:
    health:
      show-details: when_authorized
      roles: 'ROLE_ADMIN'
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState, db
    jhimetrics:
      enabled: true
  info:
    git:
      mode: full
    env:
      enabled: true
  health:
    mail:
      enabled: false
  prometheus:
    metrics:
      export:
        enabled: true
        step: 60
  observations:
    key-values:
      application: ${spring.application.name}
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    data:
      repository:
        autotime:
          enabled: true
    tags:
      application: ${spring.application.name}

feign:
  circuitbreaker:
    enabled: true

springdoc:
  api-docs:
    enabled: false

# Custom application properties
app:
  name: ${APP_NAME}
  version: ${APP_VERSION}
  description: ${APP_DESCRIPTION}
  feature:
    enable-new-feature: true  # Example of a custom feature toggle
  service:
    timeout: ${APP_SERVICE_TIMEOUT}  # Timeout for service calls in milliseconds
