# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

logging:
  level:
    ROOT: ${APP_LOG_LEVEL:INFO}
    tech.jhipster: ${APP_LOG_LEVEL:INFO}
    org.hibernate.SQL: ${APP_LOG_LEVEL:INFO}
    com.paysgift.userservice: ${APP_LOG_LEVEL:INFO}

management:
  health:
    elasticsearch:
      enabled: false
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  cloud:
    consul:
      config:
        fail-fast: false
        format: yaml
        profile-separator: '-'
      discovery:
        prefer-ip-address: true
        tags:
          - profile=${spring.profiles.active}
          - version='@project.version@'
          - git-version=${git.commit.id.describe:}
          - git-commit=${git.commit.id.abbrev:}
          - git-branch=${git.branch:}
      host: localhost
      port: 8500
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${CONTAINER_DB}:3306/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
  elasticsearch:
    uris: http://localhost:9200
  liquibase:
    contexts: dev, faker
  messages:
    cache-duration: PT1S
  thymeleaf:
    cache: false
  redis:
    host: redis-paysgift  # Use the name of the Redis container
    port: 6379

# Add the server configuration here
server:
  port: ${SERVER_PORT}  # The port your application will run on
  address: ${SERVER_ADDRESS}  # Listen on all interfaces
  forward-headers-strategy: native

jhipster:
  clientApp:
    name: User Service  # Add this line to define the client app name
  security:
    authentication:
      jwt:
        base64-secret: NDllZjM0NDRmYzQ0MTEyNzgzNjhiMjI3NzM0ZWUyNjI3MGEwNmU2YjkxYzA5YWQyMjc1OGEyNDVlZDY1YjYzNDEwNWEwMjEwYzNiZTFmMmRiNzFkOGZiYzI0Y2FiNWQ0ZjRjNjM3NWQ3YjE5ODdjMzc0NjljMjlkYTU3Y2EyYjc=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  logging:
    use-json-format: false
