package com.paysgift.transaction.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransactionDownloadAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionDownloadAllPropertiesEquals(TransactionDownload expected, TransactionDownload actual) {
        assertTransactionDownloadAutoGeneratedPropertiesEquals(expected, actual);
        assertTransactionDownloadAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionDownloadAllUpdatablePropertiesEquals(TransactionDownload expected, TransactionDownload actual) {
        assertTransactionDownloadUpdatableFieldsEquals(expected, actual);
        assertTransactionDownloadUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionDownloadAutoGeneratedPropertiesEquals(TransactionDownload expected, TransactionDownload actual) {
        assertThat(actual)
            .as("Verify TransactionDownload auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionDownloadUpdatableFieldsEquals(TransactionDownload expected, TransactionDownload actual) {
        assertThat(actual)
            .as("Verify TransactionDownload relevant properties")
            .satisfies(a -> assertThat(a.getTransactionId()).as("check transactionId").isEqualTo(expected.getTransactionId()))
            .satisfies(a -> assertThat(a.getCustomerId()).as("check customerId").isEqualTo(expected.getCustomerId()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedBy()).as("check updatedBy").isEqualTo(expected.getUpdatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionDownloadUpdatableRelationshipsEquals(TransactionDownload expected, TransactionDownload actual) {
        // empty method
    }
}
