apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: paysgift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
        env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://-kafka-service:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT
        ports:
        - containerPort: 9092
        volumeMounts:
        - name: kafka-config-volume
          mountPath: /opt/bitnami/kafka/config/server.properties
          subPath: server.properties
      volumes:
      - name: kafka-config-volume
        configMap:
          name: kafka-config